# 指定默认的环境策略
spring:
  profiles:
    active: prod

--- # 表示配置文件环境的分割
server:
  port: 8090
  profiles: prod
  servlet:
    context-path: /jt # 项目发布路径信息 默认条件下为 / (根目录)
    # tomcat 服务器默认发布路径地址为 webapps 目录下
    # /     ROOT 项目路径
    # /jt   JT   项目路径

# 指定用户配置文件信息
msg:
  username: yuanzhibx msg1
  age: 13

--- # 表示配置文件环境的分割
spring:
  profiles: test
server:
  port: 8080
  servlet:
    context-path: / # 项目发布路径信息 默认条件下为 / (根目录)
    # tomcat 服务器默认发布路径地址为 webapps 目录下
    # /     ROOT 项目路径
    # /jt   JT   项目路径

# 指定用户配置文件信息
msg:
  username: yuanzhibx msg1
  age: 13